### ISSUE TITLE
you can ban a person multiple times

### ISSUE THREAD

**Issue by NanderTGA** [nolanwhy/msgroom-custom-server#2]
The array with bans can have duplicates, making it extremely hard to unban someone.
The workaround is to spam the unban command.
The solution is to remove duplicates from this array when loading it from the JSON file by converting it to a set and then converting it back to an array. You can remove duplicates like this.
I would also recommend just keeping it as a `Set` in memory so you can use its [has() method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/has), which is more efficient.
Next, make your ban and unban commands check if a user is already banned or unbanned before trying to ban/unban.
And please also make the `admin-action` handler tell the user if they are not an admin before doing anything else and return right away.

**Comment by nolanwhy** [comment]
admin-action doesn't say anything if you aren't admin and you try executing a command (on normal msgroom) so we won't add that. but, we will fix the ban duplicates
